apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripleydemo-deployment
  labels:
    app: app-ripleydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ripleydemo
  template:
    metadata:
      labels:
        app: app-ripleydemo 
    spec:
      containers:
      - name: nodeserver
        image: oliverpm/hola-ripley:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: ripleydemo-service
spec:
  selector:
    app: app-ripleydemo 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
