apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripleydemo-deployment
  labels:
    app: app-ripleydemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-ripleydemo
  template:
    metadata:
      labels:
        app: app-ripleydemo 
    spec:
      containers:
      - name: nodeserver
        image: oliverpm/hola-ripley:latest
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: app-ripleydemo-service
spec:
  selector:
    app: app-ripleydemo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8085
